---
- name: Deploy Calculator App with Docker
  hosts: webserver
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: athira1402/scientific_calculator:latest
        source: pull

    - name: Stop and remove existing container (if any)
      community.docker.docker_container:
        name: scientific_calculator
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: scientific_calculator
        image: athira1402/scientific_calculator:latest
        state: started
        restart_policy: always
        interactive: true
        ports:
         - "8081:8080"
